// LOCAL HOST
### get all users
GET http://localhost:3000/users 

### get contacts by Id
GET http://localhost:3000/users/69081f728be5b17dfc2e2a8c

### Create contact
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "Sally 2" ,
    "lastName": "Smith",
    "email": "testss@example.com",
    "favoriteColor": "green",
    "birthday": "4/18/2000"
}

### Put contact
PUT http://localhost:3000/users 
Content-Type: application/json

{
    "firstName": "Sally 2" ,
    "lastName": "Smith",
    "email": "testss@example.com",
    "favoriteColor": "green",
    "birthday": "4/18/2000"
}

### delete contact
DELETE http://localhost:3000/users 